name: Shopify CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  deploy:
    name: Deploy to Shopify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Backup Current Theme
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          BACKUP_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          shopify theme pull --store $SHOPIFY_STORE_URL --password $SHOPIFY_PASSWORD --theme-id $BACKUP_THEME_ID --directory backup

      - name: Deploy New Code
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          shopify theme push --store $SHOPIFY_STORE_URL --password $SHOPIFY_PASSWORD --theme-id $SHOPIFY_THEME_ID

      - name: Verify Deployment
        run: curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.SHOPIFY_STORE_URL }} | grep "200"

  rollback:
    name: Rollback to Backup
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Deploy Backup Theme
        env:
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
          BACKUP_THEME_ID: ${{ secrets.BACKUP_THEME_ID }}
        run: |
          shopify theme push --store $SHOPIFY_STORE_URL --password $SHOPIFY_PASSWORD --theme-id $BACKUP_THEME_ID
